language: node_js
node_js:
- 7.5.0
before_install:
- openssl aes-256-cbc -K $encrypted_ff67dc30d4dc_key -iv $encrypted_ff67dc30d4dc_iv
  -in znn_key.enc -out ~/.ssh/znn_key -d
# - mv znn_key ~/.ssh -f
- chmod 600 ~/.ssh/znn_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/znn_key
- cp .travis/ssh_config ~/.ssh/config
after_script:
# - npm test
- ls
- rm -rf node_modules
- ls
- scp -o StrictHostKeyChecking=no -r * koaTest:/root/znn/kaoTest
- ssh koaTest 'cd znn/kaoTest && npm install && node app.js'


