language: node_js
node_js:
- 7.5.0
after_script:
npm test
- scp -o StrictHostKeyChecking=no ./src/app.js yideng:/root/code
before_install:
- openssl aes-256-cbc -K $encrypted_ff67dc30d4dc_key -iv $encrypted_ff67dc30d4dc_iv
  -in znn_key.enc -out ~/znn_key -d
- mv znn_key ~/.ssh -f
- chmod 600 ~/.ssh/znn_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/znn_key
- cp .travis/ssh_config ~/.ssh/config


